### ISSUE TITLE
This... isn't correct at all.

### ISSUE THREAD

**Issue by rodneymorgan225** [all-contributors/all-contributors#774]
This... isn't correct at all.

The workflow is parsed in a string context (except for numerals and booleans), so JavaScript truthiness is irrelevant. There's no way to define a true JavaScript `NaN` or `undefined` in YML, you end up with the strings `'NaN'` or `'undefined'`. Nearly any string will evaluate `true`.

In this workflow:
```yml
    strategy:
      matrix:
        runme:
          - NaN
          - undefined
          - yes
          - no
          - false
          - 0
          - 1
          - -0

    steps:
      - name: true-path
        if: matrix.runme
        run: echo "${{ matrix.runme }} evaluates true"
      - name: false-path
        if: '! matrix.runme'
        run: echo "${{ matrix.runme }} evaluates false"
```

...The only `matrix.runme` values for which `false-path` will be executed are `false` and `0`. (And `-0`, technically, but that's only because it's interpreted as `0`. There's no distinction in YAML.) All of the others will evaluate `true`.

_Originally posted by @ferdnyc in https://github.com/github/docs/pull/31252#discussion_r1467130276_
